---
kind: pipeline
type: docker
name: yaojuntian-web

steps:
- name: install
  image: node:lts-alpine
  commands:
   - npm i  --registry=https://registry.npm.taobao.org
- name: build
  image: node:lts-alpine
  commands:
   - npm run prod
