---
kind: pipeline
type: docker
name: yaojuntian-web
steps:
- name: install
  image: node:lts-alpine
  commands:
   - npm i  --registry=https://registry.npm.taobao.org
- name: build
  image: node:lts-alpine
  commands:
   - npm run prod
- name: rsync
  image: drillster/drone-rsync
  environment:
    RSYNC_KEY:
      from_secret: yaojuntian_key
  settings:
    hosts:
      - 123.206.83.64
    source: dist/*
    target: /projects/html
    secrets: [ yaojuntian_key ]
- name: inform
  image: curlimages/curl:7.67.0
  commands:
   - |
     curl 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=b0d94e6f-208f-43e5-afac-8f135dd34676' -H 'Content-Type: application/json' -d '{"msgtype": "text","text": {"content": "部署完成"}}'